name: Flatpak
on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flatpak-release:
    name: Flatpak (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged
    strategy:
      matrix:
        include:
        - arch: x86_64
          runner: ubuntu-latest
        - arch: aarch64
          runner: ubuntu-24.04-arm
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.6
      with:
        bundle: butler.flatpak
        manifest-path: com.cassidyjames.butler.json
        cache-key: "flatpak-builder-${{ github.sha }}-${{ matrix.arch }}"
        arch: ${{ matrix.arch }}
