name: Lint
on:
  pull_request:

jobs:
  lint:
    name: Vala Lint
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: io.elementary.vala-lint -d .
