name: Mirror
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: GitLab
        uses: roostorg/mirror@main
        with:
          destination: https://gitlab.com/cassidyjames/butler.git
          token: ${{ secrets.GITLAB_TOKEN }}

      - name: Codeberg
        uses: roostorg/mirror@main
        with:
          destination: https://codeberg.org/cassidyjames/butler.git
          token: ${{ secrets.CODEBERG_TOKEN }}
          token_username: cassidyjames

      - name: Tangled
        uses: roostorg/mirror@main
        with:
          destination: git@tangled.org:cassidyjames.com/butler
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_known_hosts: ${{ secrets.TANGLED_KNOWN_HOSTS }}
