name: Release

on:
  release:
    types: [published]

jobs:
  flatpak:
    name: Flatpak (Release, ${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged
    strategy:
      matrix:
        include:
        - arch: x86_64
          runner: ubuntu-latest
        - arch: aarch64
          runner: ubuntu-24.04-arm
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.6
      with:
        bundle: butler.flatpak
        manifest-path: com.cassidyjames.butler.json
        cache-key: "flatpak-builder-${{ github.sha }}-${{ matrix.arch }}"
        arch: ${{ matrix.arch }}

  upload:
    name: Upload to Release
    runs-on: ubuntu-latest
    needs: flatpak
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: butler-*.flatpak
        merge-multiple: true
    - name: Upload Flatpak to release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} \
          butler*.flatpak \
          --repo ${{ github.repository }}
